import random
from django.contrib.auth import get_user_model
from django.utils import timezone
from biblioteca_app.models import *

def create_users():
    User = get_user_model()
    users = [
        {'username': 'john_doe', 'nom': 'John', 'cognoms': 'Doe', 'any_naixement': '1990-05-15', 'correu_ieti': 'john.doe@iesesteveterradas.cat', 'tipus': 'alumne'},
        {'username': 'profe_jane','nom': 'Jane', 'cognoms': 'Smith', 'any_naixement': '1985-03-20', 'correu_ieti': 'jane.smith@iesesteveterradas.cat', 'tipus': 'professor'},
        {'username': 'admin_admin', 'nom': 'Admin', 'cognoms': 'Admin', 'any_naixement': '1980-10-10', 'correu_ieti': 'admin@iesesteveterradas.cat', 'tipus': 'admin'},
    ]
    for user_data in users:
        User.objects.create_user(email=user_data['correu_ieti'], password='password123', **user_data)

# def create_items():
#     items = [
#         {'titol': 'El gran Gatsby', 'autor': 'F. Scott Fitzgerald', 'descripcio': 'Novela clásica que retrata la vida en la alta sociedad estadounidense durante la década de 1920.', 'lloc_edicio': 'Nueva York', 'any': 1925, 'pais': 'Estados Unidos', 'signatura': 'FIC-001', 'exemplars': 5, 'url': 'https://example.com', 'imatge': 'gatsby.jpg', 'mides': '14x21', 'procedencia': 'Donación biblioteca', 'caracteristiques': 'Edición de tapa dura', 'altra_informacio': 'Incluye notas al pie de página'},
#         {'titol': 'Cien años de soledad', 'autor': 'Gabriel García Márquez', 'descripcio': 'Obra maestra del realismo mágico latinoamericano que narra la historia de la familia Buendía en el pueblo ficticio de Macondo.', 'lloc_edicio': 'Bogotá', 'any': 1967, 'pais': 'Colombia', 'signatura': 'FIC-002', 'exemplars': 3, 'url': 'https://example.com', 'imatge': 'cien_anos_soledad.jpg', 'mides': '15x23', 'procedencia': 'Compra biblioteca', 'caracteristiques': 'Edición de bolsillo', 'altra_informacio': 'Versión revisada por el autor'},
#     ]
#     for item_data in items:
#         ItemCataleg.objects.create(**item_data)

def create_prestecs():
    users = get_user_model().objects.all()
    items = ItemCataleg.objects.all()
    for _ in range(5):
        user = random.choice(users)
        item = random.choice(items)
        Prestecs.objects.create(usuari=user, item_cataleg=item, data_prestec=timezone.now(), data_retorn=timezone.now() + timezone.timedelta(days=14), data_limit=timezone.now() + timezone.timedelta(days=30))

def create_reserves():
    users = get_user_model().objects.all()
    items = ItemCataleg.objects.all()
    for _ in range(3):
        user = random.choice(users)
        item = random.choice(items)
        Reserves.objects.create(usuari=user, item_cataleg=item, data_reserva=timezone.now())

def create_peticions():
    users = get_user_model().objects.all()
    for _ in range(2):
        user = random.choice(users)
        Peticions.objects.create(usuari=user, text='Solicitud de información', is_accepted=False)

def create_books():
    books = [
        {
            'titol': 'El principito',
            'autor': 'Antoine de Saint-Exupéry',
            'descripcio': 'Fábula filosófica sobre la amistad, el amor y la búsqueda del sentido de la vida.',
            'lloc_edicio': 'París',
            'any': 1943,
            'pais': 'Francia',
            'signatura': 'FIC-007',
            'exemplars': 6,
            'url': 'https://example.com',
            'imatge': 'el_principito.jpg',
            'mides': '10x15',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Una obra universalmente aclamada, tanto por niños como por adultos.',
            'CDU': 'FIC-007',
            'ISBN': 9788478887213,
            'editorial': 'Salvat Editores',
            'colleccio': 'N/A',
            'pagines': 96,
            'descriptors': 'Fábula, Filosofía, Infancia',
            'resum': 'Fábula filosófica sobre la amistad, el amor y la búsqueda del sentido de la vida.',
            'volums': 1,
        },
        {
            'titol': 'Orgullo y prejuicio',
            'autor': 'Jane Austen',
            'descripcio': 'Clásico de la literatura inglesa que narra la historia de Elizabeth Bennet y el señor Darcy.',
            'lloc_edicio': 'Londres',
            'any': 1813,
            'pais': 'Reino Unido',
            'signatura': 'FIC-008',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'orgullo_prejuicio.jpg',
            'mides': '12x18',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa blanda',
            'altra_informacio': 'Una de las novelas más conocidas de Jane Austen.',
            'CDU': 'FIC-008',
            'ISBN': 9788491050783,
            'editorial': 'Alba Editorial',
            'colleccio': 'Clásica Maior',
            'pagines': 432,
            'descriptors': 'Romance, Clásico, Sociedad',
            'resum': 'Clásico de la literatura inglesa que narra la historia de Elizabeth Bennet y el señor Darcy.',
            'volums': 1,
        },
        {
            'titol': 'Don Quijote de la Mancha',
            'autor': 'Miguel de Cervantes',
            'descripcio': 'Novela que narra las aventuras de un hidalgo que enloquece tras leer demasiados libros de caballería.',
            'lloc_edicio': 'Madrid',
            'any': 1605,
            'pais': 'España',
            'signatura': 'FIC-009',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'don_quijote.jpg',
            'mides': '16x24',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de lujo',
            'altra_informacio': 'Considerada una de las mejores obras de la literatura universal.',
            'CDU': 'FIC-009',
            'ISBN': 9788420712113,
            'editorial': 'Espasa Calpe',
            'colleccio': 'Clásicos',
            'pagines': 1064,
            'descriptors': 'Sátira, Aventura, Humor',
            'resum': 'Novela que narra las aventuras de un hidalgo que enloquece tras leer demasiados libros de caballería.',
            'volums': 2,
        },
        {
            'titol': 'Matar un ruiseñor',
            'autor': 'Harper Lee',
            'descripcio': 'Novela que aborda temas como la injusticia racial y la pérdida de la inocencia en el sur de Estados Unidos.',
            'lloc_edicio': 'Nueva York',
            'any': 1960,
            'pais': 'Estados Unidos',
            'signatura': 'FIC-010',
            'exemplars': 5,
            'url': 'https://example.com',
            'imatge': 'matar_ruiseñor.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Ganadora del Premio Pulitzer en 1961.',
            'CDU': 'FIC-010',
            'ISBN': 9788491051186,
            'editorial': 'Salamandra',
            'colleccio': 'N/A',
            'pagines': 384,
            'descriptors': 'Injusticia racial, Infancia, Sur de Estados Unidos',
            'resum': 'Novela que aborda temas como la injusticia racial y la pérdida de la inocencia en el sur de Estados Unidos.',
            'volums': 1,
        },
        {
            'titol': 'Los miserables',
            'autor': 'Victor Hugo',
            'descripcio': 'Novela que sigue la vida de varios personajes durante un periodo tumultuoso en la historia de Francia.',
            'lloc_edicio': 'París',
            'any': 1862,
            'pais': 'Francia',
            'signatura': 'FIC-011',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'los_miserables.jpg',
            'mides': '15x23',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición especial con ilustraciones.',
            'altra_informacio': 'Una obra maestra de la literatura francesa.',
            'CDU': 'FIC-011',
            'ISBN': 9788491050615,
            'editorial': 'Penguin Clásicos',
            'colleccio': 'N/A',
            'pagines': 1728,
            'descriptors': 'Historia, Redención, Revolución',
            'resum': 'Novela que sigue la vida de varios personajes durante un periodo tumultuoso en la historia de Francia.',
            'volums': 1,
        },
        {
            'titol': 'Rayuela',
            'autor': 'Julio Cortázar',
            'descripcio': 'Novela experimental que desafía las convenciones narrativas tradicionales.',
            'lloc_edicio': 'Buenos Aires',
            'any': 1963,
            'pais': 'Argentina',
            'signatura': 'FIC-012',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'rayuela.jpg',
            'mides': '12x18',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa blanda',
            'altra_informacio': 'Una de las obras más importantes del boom latinoamericano.',
            'CDU': 'FIC-012',
            'ISBN': 9788432217895,
            'editorial': 'Seix Barral',
            'colleccio': 'Biblioteca Breve',
            'pagines': 576,
            'descriptors': 'Experimental, Literatura latinoamericana, Juego',
            'resum': 'Novela experimental que desafía las convenciones narrativas tradicionales.',
            'volums': 1,
        },
        {
            'titol': 'Anna Karenina',
            'autor': 'León Tolstói',
            'descripcio': 'Novela que explora temas como el amor, la moralidad y la hipocresía en la alta sociedad rusa del siglo XIX.',
            'lloc_edicio': 'San Petersburgo',
            'any': 1877,
            'pais': 'Rusia',
            'signatura': 'FIC-013',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'anna_karenina.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Considerada una de las mejores novelas de todos los tiempos.',
            'CDU': 'FIC-013',
            'ISBN': 9788491050943,
            'editorial': 'DeBolsillo',
            'colleccio': 'Contemporánea',
            'pagines': 1024,
            'descriptors': 'Amor, Sociedad, Moralidad',
            'resum': 'Novela que explora temas como el amor, la moralidad y la hipocresía en la alta sociedad rusa del siglo XIX.',
            'volums': 1,
        },
        {
            'titol': 'La metamorfosis',
            'autor': 'Franz Kafka',
            'descripcio': 'Relato que narra la historia de Gregor Samsa, quien se despierta un día transformado en un insecto gigante.',
            'lloc_edicio': 'Leipzig',
            'any': 1915,
            'pais': 'Alemania',
            'signatura': 'FIC-014',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'la_metamorfosis.jpg',
            'mides': '12x18',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa blanda',
            'altra_informacio': 'Una obra fundamental del existencialismo.',
            'CDU': 'FIC-014',
            'ISBN': 9788437607466,
            'editorial': 'Cátedra',
            'colleccio': 'Letras Universales',
            'pagines': 224,
            'descriptors': 'Existencialismo, Transformación, Alegoría',
            'resum': 'Relato que narra la historia de Gregor Samsa, quien se despierta un día transformado en un insecto gigante.',
            'volums': 1,
        },
        {
            'titol': 'El retrato de Dorian Gray',
            'autor': 'Oscar Wilde',
            'descripcio': 'Novela que examina la vanidad, el hedonismo y la moralidad a través de la historia de un hombre inmortal.',
            'lloc_edicio': 'Londres',
            'any': 1890,
            'pais': 'Reino Unido',
            'signatura': 'FIC-015',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'retrato_dorian_gray.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Una obra clave del decadentismo inglés.',
            'CDU': 'FIC-015',
            'ISBN': 9788491051971,
            'editorial': 'DeBolsillo',
            'colleccio': 'Contemporánea',
            'pagines': 304,
            'descriptors': 'Vanidad, Inmortalidad, Decadencia',
            'resum': 'Novela que examina la vanidad, el hedonismo y la moralidad a través de la historia de un hombre inmortal.',
            'volums': 1,
        },
        {
            'titol': 'El gran Gatsby',
            'autor': 'F. Scott Fitzgerald',
            'descripcio': 'Novela que retrata la vida de la alta sociedad estadounidense durante la década de 1920.',
            'lloc_edicio': 'Nueva York',
            'any': 1925,
            'pais': 'Estados Unidos',
            'signatura': 'FIC-016',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'gran_gatsby.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa blanda',
            'altra_informacio': 'Considerada una de las mejores novelas estadounidenses del siglo XX.',
            'CDU': 'FIC-016',
            'ISBN': 9788491050455,
            'editorial': 'DeBolsillo',
            'colleccio': 'Contemporánea',
            'pagines': 256,
            'descriptors': 'Sociedad, Riqueza, Amor',
            'resum': 'Novela que retrata la vida de la alta sociedad estadounidense durante la década de 1920.',
            'volums': 1,
        },
        {
            'titol': 'Ulises',
            'autor': 'James Joyce',
            'descripcio': 'Novela modernista que narra un día en la vida de Leopold Bloom en Dublín.',
            'lloc_edicio': 'París',
            'any': 1922,
            'pais': 'Francia',
            'signatura': 'FIC-017',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'ulises.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa dura',
            'altra_informacio': 'Considerada una de las obras más importantes de la literatura moderna.',
            'CDU': 'FIC-017',
            'ISBN': 9788491050707,
            'editorial': 'DeBolsillo',
            'colleccio': 'Contemporánea',
            'pagines': 1040,
            'descriptors': 'Modernismo, Stream of consciousness, Dublín',
            'resum': 'Novela modernista que narra un día en la vida de Leopold Bloom en Dublín.',
            'volums': 1,
        },
        {
            'titol': 'Crónica de una muerte anunciada',
            'autor': 'Gabriel García Márquez',
            'descripcio': 'Novela que relata los eventos que conducen al asesinato de Santiago Nasar.',
            'lloc_edicio': 'Buenos Aires',
            'any': 1981,
            'pais': 'Argentina',
            'signatura': 'FIC-018',
            'exemplars': 5,
            'url': 'https://example.com',
            'imatge': 'cronica_muerte_anunciada.jpg',
            'mides': '12x18',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Una de las obras más conocidas de Gabriel García Márquez.',
            'CDU': 'FIC-018',
            'ISBN': 9788420492129,
            'editorial': 'Alianza Editorial',
            'colleccio': 'Contemporánea',
            'pagines': 128,
            'descriptors': 'Asesinato, Latinoamérica, Cultura',
            'resum': 'Novela que relata los eventos que conducen al asesinato de Santiago Nasar.',
            'volums': 1,
        },
        {
            'titol': 'El nombre de la rosa',
            'autor': 'Umberto Eco',
            'descripcio': 'Novela histórica y de misterio que tiene lugar en una abadía benedictina en el siglo XIV.',
            'lloc_edicio': 'Milán',
            'any': 1980,
            'pais': 'Italia',
            'signatura': 'FIC-019',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'nombre_rosa.jpg',
            'mides': '14x21',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de tapa dura',
            'altra_informacio': 'Best-seller internacional y adaptada al cine.',
            'CDU': 'FIC-019',
            'ISBN': 9788420472275,
            'editorial': 'Planeta',
            'colleccio': 'Autores Españoles e Iberoamericanos',
            'pagines': 592,
            'descriptors': 'Historia, Misterio, Religión',
            'resum': 'Novela histórica y de misterio que tiene lugar en una abadía benedictina en el siglo XIV.',
            'volums': 1,
        },
        {
            'titol': 'Pedro Páramo',
            'autor': 'Juan Rulfo',
            'descripcio': 'Novela que narra la búsqueda del protagonista para encontrar a su padre en un pueblo fantasmal en México.',
            'lloc_edicio': 'México DF',
            'any': 1955,
            'pais': 'México',
            'signatura': 'FIC-020',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'pedro_paramo.jpg',
            'mides': '12x18',
            'procedencia': 'Compra biblioteca',
            'caracteristiques': 'Edición de bolsillo',
            'altra_informacio': 'Una de las obras maestras de la literatura latinoamericana.',
            'CDU': 'FIC-020',
            'ISBN': 9789684111726,
            'editorial': 'Fondo de Cultura Económica',
            'colleccio': 'Colección Popular',
            'pagines': 152,
            'descriptors': 'Búsqueda, Realismo mágico, México',
            'resum': 'Novela que narra la búsqueda del protagonista para encontrar a su padre en un pueblo fantasmal en México.',
            'volums': 1,
        },
    ]
    for book_data in books:
        Llibre.objects.create(**book_data)

def create_cds():
    cds = [
        {
            'titol': 'The Dark Side of the Moon',
            'autor': 'Pink Floyd',
            'descripcio': 'Álbum icónico de rock progresivo que aborda temas como la vida, la muerte y la locura.',
            'lloc_edicio': 'Londres',
            'any': 1973,
            'pais': 'Reino Unido',
            'signatura': 'CD-001',
            'exemplars': 5,
            'url': 'https://example.com',
            'imatge': 'dark_side_moon.jpg',
            'mides': '12x12',
            'procedencia': 'Compra tienda de discos',
            'caracteristiques': 'Edición remasterizada',
            'altra_informacio': 'Considerado uno de los mejores álbumes de todos los tiempos.',
            'discografia': 'Pink Floyd Records',
            'estil': 'Rock progresivo',
            'duracio': '00:43:00',
        },
        {
            'titol': 'Thriller',
            'autor': 'Michael Jackson',
            'descripcio': 'Álbum revolucionario que fusiona pop, rock, funk y disco, con éxitos como "Billie Jean" y "Thriller".',
            'lloc_edicio': 'Los Ángeles',
            'any': 1982,
            'pais': 'Estados Unidos',
            'signatura': 'CD-002',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'thriller.jpg',
            'mides': '12x12',
            'procedencia': 'Compra tienda de discos',
            'caracteristiques': 'Edición especial con libreto',
            'altra_informacio': 'El álbum más vendido de todos los tiempos.',
            'discografia': 'Epic Records',
            'estil': 'Pop, R&B',
            'duracio': '00:42:19',
        },
        {
            'titol': 'Abbey Road',
            'autor': 'The Beatles',
            'descripcio': 'Álbum legendario que incluye canciones como "Come Together" y "Here Comes the Sun".',
            'lloc_edicio': 'Londres',
            'any': 1969,
            'pais': 'Reino Unido',
            'signatura': 'CD-003',
            'exemplars': 6,
            'url': 'https://example.com',
            'imatge': 'abbey_road.jpg',
            'mides': '12x12',
            'procedencia': 'Compra tienda de discos',
            'caracteristiques': 'Edición remasterizada',
            'altra_informacio': 'Considerado uno de los mejores álbumes de The Beatles.',
            'discografia': 'Apple Records',
            'estil': 'Rock',
            'duracio': '00:47:23',
        },
        {
            'titol': 'Back in Black',
            'autor': 'AC/DC',
            'descripcio': 'Álbum icónico de hard rock con éxitos como "Back in Black" y "You Shook Me All Night Long".',
            'lloc_edicio': 'Nueva York',
            'any': 1980,
            'pais': 'Estados Unidos',
            'signatura': 'CD-004',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'back_in_black.jpg',
            'mides': '12x12',
            'procedencia': 'Compra tienda de discos',
            'caracteristiques': 'Edición de colección',
            'altra_informacio': 'Uno de los álbumes más vendidos de todos los tiempos.',
            'discografia': 'Atlantic Records',
            'estil': 'Hard rock',
            'duracio': '00:42:11',
        },
        {
            'titol': 'Rumours',
            'autor': 'Fleetwood Mac',
            'descripcio': 'Álbum de pop rock que incluye éxitos como "Go Your Own Way" y "Dreams".',
            'lloc_edicio': 'Los Ángeles',
            'any': 1977,
            'pais': 'Estados Unidos',
            'signatura': 'CD-005',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'rumours.jpg',
            'mides': '12x12',
            'procedencia': 'Compra tienda de discos',
            'caracteristiques': 'Edición especial con notas de producción',
            'altra_informacio': 'Uno de los álbumes más vendidos de la historia.',
            'discografia': 'Warner Bros. Records',
            'estil': 'Pop rock',
            'duracio': '00:39:43',
        },
    ]

    for cd_data in cds:
        CD.objects.create(**cd_data)

def create_dvds():
    dvds = [
        {
            'titol': 'Pulp Fiction',
            'autor': 'Quentin Tarantino',
            'descripcio': 'Película que entrelaza varias historias en el mundo del crimen organizado de Los Ángeles.',
            'lloc_edicio': 'Los Ángeles',
            'any': 1994,
            'pais': 'Estados Unidos',
            'signatura': 'DVD-001',
            'exemplars': 5,
            'url': 'https://example.com',
            'imatge': 'pulp_fiction.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición especial con contenido adicional',
            'altra_informacio': 'Ganadora de la Palma de Oro en el Festival de Cannes.',
            'discografia': 'Miramax Films',
            'estil': 'Drama, Crimen',
            'duracio': '02:34:00',
        },
        {
            'titol': 'El Padrino',
            'autor': 'Francis Ford Coppola',
            'descripcio': 'Epopeya de la familia criminal Corleone, dirigida por el patriarca Vito Corleone.',
            'lloc_edicio': 'Los Ángeles',
            'any': 1972,
            'pais': 'Estados Unidos',
            'signatura': 'DVD-002',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'el_padrino.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición de coleccionista',
            'altra_informacio': 'Considerada una de las mejores películas de la historia del cine.',
            'discografia': 'Paramount Pictures',
            'estil': 'Drama, Crimen',
            'duracio': '02:55:00',
        },
        {
            'titol': 'Forrest Gump',
            'autor': 'Robert Zemeckis',
            'descripcio': 'Historia de un hombre con discapacidad intelectual que vive una vida extraordinaria.',
            'lloc_edicio': 'Los Ángeles',
            'any': 1994,
            'pais': 'Estados Unidos',
            'signatura': 'DVD-003',
            'exemplars': 6,
            'url': 'https://example.com',
            'imatge': 'forrest_gump.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición especial con comentarios del director',
            'altra_informacio': 'Ganadora de varios premios Óscar, incluyendo Mejor Película.',
            'discografia': 'Paramount Pictures',
            'estil': 'Drama, Comedia',
            'duracio': '02:22:00',
        },
        {
            'titol': 'El Señor de los Anillos: La Comunidad del Anillo',
            'autor': 'Peter Jackson',
            'descripcio': 'Adaptación cinematográfica del primer libro de la trilogía de J.R.R. Tolkien.',
            'lloc_edicio': 'Wellington',
            'any': 2001,
            'pais': 'Nueva Zelanda',
            'signatura': 'DVD-004',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'comunidad_anillo.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición extendida',
            'altra_informacio': 'Ganadora de varios premios de la Academia, incluyendo Mejor Fotografía.',
            'discografia': 'New Line Cinema',
            'estil': 'Fantasía, Aventura',
            'duracio': '03:48:00',
        },
        {
            'titol': 'Interestelar',
            'autor': 'Christopher Nolan',
            'descripcio': 'Película que sigue a un grupo de astronautas que viajan a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.',
            'lloc_edicio': 'Los Ángeles',
            'any': 2014,
            'pais': 'Estados Unidos',
            'signatura': 'DVD-005',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'interestelar.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición especial en steelbook',
            'altra_informacio': 'Reconocida por sus efectos visuales y su banda sonora.',
            'discografia': 'Paramount Pictures',
            'estil': 'Ciencia ficción, Drama',
            'duracio': '02:49:00',
        },
    ]
    
    for dvd_data in dvds:
        DVD.objects.create(**dvd_data)

def create_brs():
    brs = [
        {
            'titol': 'Inception',
            'autor': 'Christopher Nolan',
            'descripcio': 'Película que explora el mundo de los sueños a través de la tecnología de la infiltración.',
            'lloc_edicio': 'Los Ángeles',
            'any': 2010,
            'pais': 'Estados Unidos',
            'signatura': 'BR-001',
            'exemplars': 5,
            'url': 'https://example.com',
            'imatge': 'inception.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición especial con comentarios del director',
            'altra_informacio': 'Ganadora de cuatro premios de la Academia.',
            'discografia': 'Warner Bros. Pictures',
            'estil': 'Ciencia ficción, Acción',
            'duracio': '02:28:00',
        },
        {
            'titol': 'The Matrix',
            'autor': 'The Wachowskis',
            'descripcio': 'Película que presenta un mundo virtual simulado, donde los humanos son esclavos de las máquinas.',
            'lloc_edicio': 'Los Ángeles',
            'any': 1999,
            'pais': 'Estados Unidos',
            'signatura': 'BR-002',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'the_matrix.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición remasterizada en 4K',
            'altra_informacio': 'Ganadora de cuatro premios Óscar.',
            'discografia': 'Warner Bros. Pictures',
            'estil': 'Ciencia ficción, Acción',
            'duracio': '02:16:00',
        },
        {
            'titol': 'Interstellar',
            'autor': 'Christopher Nolan',
            'descripcio': 'Película que sigue a un grupo de astronautas en un viaje interestelar para encontrar un nuevo hogar para la humanidad.',
            'lloc_edicio': 'Los Ángeles',
            'any': 2014,
            'pais': 'Estados Unidos',
            'signatura': 'BR-003',
            'exemplars': 6,
            'url': 'https://example.com',
            'imatge': 'interstellar.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición de colección en steelbook',
            'altra_informacio': 'Reconocida por sus efectos visuales y su banda sonora.',
            'discografia': 'Paramount Pictures',
            'estil': 'Ciencia ficción, Drama',
            'duracio': '02:49:00',
        },
        {
            'titol': 'The Avengers',
            'autor': 'Joss Whedon',
            'descripcio': 'Película que reúne a varios superhéroes de Marvel para luchar contra una amenaza común.',
            'lloc_edicio': 'Los Ángeles',
            'any': 2012,
            'pais': 'Estados Unidos',
            'signatura': 'BR-004',
            'exemplars': 3,
            'url': 'https://example.com',
            'imatge': 'the_avengers.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición especial con escenas eliminadas',
            'altra_informacio': 'Una de las películas más taquilleras de todos los tiempos.',
            'discografia': 'Marvel Studios',
            'estil': 'Acción, Aventura',
            'duracio': '02:23:00',
        },
        {
            'titol': 'Avatar',
            'autor': 'James Cameron',
            'descripcio': 'Película que transporta a los espectadores a un mundo alienígena donde la humanidad lucha por recursos naturales.',
            'lloc_edicio': 'Los Ángeles',
            'any': 2009,
            'pais': 'Estados Unidos',
            'signatura': 'BR-005',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'avatar.jpg',
            'mides': '5x7',
            'procedencia': 'Compra tienda de películas',
            'caracteristiques': 'Edición extendida en 3D',
            'altra_informacio': 'Ganadora de tres premios de la Academia, incluyendo Mejor Dirección de Arte.',
            'discografia': '20th Century Fox',
            'estil': 'Ciencia ficción, Aventura',
            'duracio': '02:58:00',
        },
    ]

    for br_data in brs:
        BR.objects.create(**br_data)

def create_dispositius():
    dispositius = [
        {
            'titol': 'iPhone 12',
            'autor': 'Apple Inc.',
            'descripcio': 'Teléfono inteligente con pantalla Super Retina XDR, chip A14 Bionic y sistema de doble cámara.',
            'lloc_edicio': 'Cupertino',
            'any': 2020,
            'pais': 'Estados Unidos',
            'signatura': 'DISP-001',
            'exemplars': 10,
            'url': 'https://example.com',
            'imatge': 'iphone_12.jpg',
            'mides': '6.1 pulgadas',
            'procedencia': 'Compra tienda de electrónicos',
            'caracteristiques': 'Resistente al agua y al polvo, Face ID, carga inalámbrica',
            'altra_informacio': 'Disponible en diferentes capacidades de almacenamiento.',
            'marca': 'Apple',
            'model': 'iPhone 12',
            'capacitat': '64GB, 128GB, 256GB',
            'bateria': 'Batería de iones de litio recargable incorporada',
        },
        {
            'titol': 'Samsung Galaxy S21',
            'autor': 'Samsung Electronics',
            'descripcio': 'Teléfono inteligente con pantalla Dynamic AMOLED 2X, procesador Exynos 2100 y sistema de triple cámara.',
            'lloc_edicio': 'Seúl',
            'any': 2021,
            'pais': 'Corea del Sur',
            'signatura': 'DISP-002',
            'exemplars': 8,
            'url': 'https://example.com',
            'imatge': 'galaxy_s21.jpg',
            'mides': '6.2 pulgadas',
            'procedencia': 'Compra tienda de electrónicos',
            'caracteristiques': 'Resistente al agua y al polvo, reconocimiento facial, carga inalámbrica',
            'altra_informacio': 'Disponible en diferentes colores y capacidades de almacenamiento.',
            'marca': 'Samsung',
            'model': 'Galaxy S21',
            'capacitat': '128GB, 256GB',
            'bateria': 'Batería de iones de litio recargable incorporada',
        },
        {
            'titol': 'MacBook Pro',
            'autor': 'Apple Inc.',
            'descripcio': 'Ordenador portátil con procesador M1, pantalla Retina, Touch Bar y Touch ID.',
            'lloc_edicio': 'Cupertino',
            'any': 2020,
            'pais': 'Estados Unidos',
            'signatura': 'DISP-003',
            'exemplars': 6,
            'url': 'https://example.com',
            'imatge': 'macbook_pro.jpg',
            'mides': '13 pulgadas',
            'procedencia': 'Compra tienda de electrónicos',
            'caracteristiques': 'Touch Bar con sensor Touch ID integrado, altavoces estéreo con sonido de alta fidelidad',
            'altra_informacio': 'Disponible en diferentes configuraciones de procesador y almacenamiento.',
            'marca': 'Apple',
            'model': 'MacBook Pro',
            'capacitat': '256GB, 512GB, 1TB',
            'bateria': 'Batería de polímero de litio integrada',
        },
        {
            'titol': 'Sony PlayStation 5',
            'autor': 'Sony Corporation',
            'descripcio': 'Consola de videojuegos con arquitectura de última generación, unidad de estado sólido y controlador DualSense.',
            'lloc_edicio': 'Tokio',
            'any': 2020,
            'pais': 'Japón',
            'signatura': 'DISP-004',
            'exemplars': 4,
            'url': 'https://example.com',
            'imatge': 'playstation_5.jpg',
            'mides': '15.4 x 10.2 x 4.1 pulgadas',
            'procedencia': 'Compra tienda de electrónicos',
            'caracteristiques': 'Soporte para ray tracing, retrocompatibilidad con juegos de PlayStation 4',
            'altra_informacio': 'Incluye un controlador inalámbrico DualSense y soporte para accesorios PlayStation VR.',
            'marca': 'Sony',
            'model': 'PlayStation 5',
            'capacitat': '825GB SSD',
            'bateria': 'No aplica',
        },
        {
            'titol': 'Amazon Echo Dot',
            'autor': 'Amazon.com, Inc.',
            'descripcio': 'Altavoz inteligente con asistente virtual Alexa, diseñado para controlar dispositivos domésticos inteligentes y reproducir música.',
            'lloc_edicio': 'Seattle',
            'any': 2018,
            'pais': 'Estados Unidos',
            'signatura': 'DISP-005',
            'exemplars': 7,
            'url': 'https://example.com',
            'imatge': 'echo_dot.jpg',
            'mides': '3.9 x 3.9 x 1.7 pulgadas',
            'procedencia': 'Compra tienda de electrónicos',
            'caracteristiques': 'Micrófonos de campo lejano para reconocimiento de voz, altavoz de 1.6 pulgadas para audio',
            'altra_informacio': 'Compatible con dispositivos inteligentes de hogar, como luces, termostatos y cerraduras.',
            'marca': 'Amazon',
            'model': 'Echo Dot',
            'capacitat': 'No aplica',
            'bateria': 'No aplica',
        },
    ]
    
    for dispositiu_data in dispositius:
        Dispositiu.objects.create(**dispositiu_data)

create_users()
# create_items()    # <-- Esto no.
create_prestecs()
create_reserves()
create_peticions()
create_books()
create_cds()
create_dvds()
create_brs()
create_dispositius()