# Generated by Django 5.0.4 on 2024-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestecs',
            name='data_retorn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
