# Generated by Django 5.0.4 on 2024-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='imatge_perfil',
            field=models.ImageField(default='static/img/user_default.webp', upload_to='static/img/profiles/'),
        ),
    ]
