# Generated by Django 5.0.4 on 2024-04-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='is_superuser',
        ),
    ]
