# Generated by Django 5.0.4 on 2024-04-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=9)),
                ('curs', models.CharField(max_length=50)),
            ],
        ),
    ]
