# Generated by Django 5.0.4 on 2024-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_usuari_centre_alter_usuari_tipus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcataleg',
            name='llengua',
            field=models.CharField(default='Català', max_length=100),
        ),
    ]
