# Generated by Django 5.0.4 on 2024-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_remove_usuari_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llibre',
            name='ISBN',
            field=models.IntegerField(),
        ),
    ]
