# Generated by Django 5.0.4 on 2024-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_itemcataleg_llengua'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcataleg',
            name='centre',
            field=models.CharField(default='I.E.S. Esteve Terradas i Illa', max_length=100),
        ),
    ]
