# Generated by Django 5.0.4 on 2024-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_usuari_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUsuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usuari',
            name='tipus',
            field=models.CharField(choices=[('alumne', 'Alumne'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
