# Generated by Django 5.0.4 on 2024-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_itemcataleg_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcataleg',
            name='tipus',
            field=models.CharField(choices=[('llibre', 'Llibre'), ('cd', 'CD'), ('dvd', 'DVD'), ('br', 'BR'), ('dispositiu', 'Dispositiu')], default='llibre', max_length=100),
        ),
    ]
