# Generated by Django 5.0.4 on 2024-04-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0005_superusuari_alter_usuari_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.usuari'),
        ),
        migrations.AlterField(
            model_name='peticions',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.usuari'),
        ),
        migrations.AlterField(
            model_name='prestecs',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.usuari'),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.usuari'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
