# Generated by Django 5.0.4 on 2024-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_alter_logs_usuari_alter_peticions_usuari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superusuari',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
