# Generated by Django 5.0.4 on 2024-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0008_delete_superusuari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='tipus',
            field=models.CharField(choices=[('alumne', 'Alumne'), ('professor', 'Professor'), ('admin', 'Admin'), ('super-usuari', 'Super Usuari')], max_length=20),
        ),
    ]
