# Generated by Django 5.0.4 on 2024-04-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0010_alter_usuari_correu_ieti_alter_usuari_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llibre',
            old_name='collecio',
            new_name='colleccio',
        ),
    ]
